<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\PermissionRegistrar;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RoleAndPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $role_admin = Role::create(['name' => 'admin']);
        $role_supervisor = Role::create(['name' => 'supervisor']);
        $role_curator = Role::create(['name' => 'curator']);
        $role_seller = Role::create(['name' => 'seller']);
        $role_school_principal = Role::create(['name' => 'school-principal']);
        $role_teacher = Role::create(['name' => 'teacher']);
        $role_student = Role::create(['name' => 'student']);
        Role::create(['name' => 'super-admin']);

        $role_adm_regional = Role::create(['name' => 'admregional']);
        $role_corrector = Role::create(['name' => 'corrector']);
        $role_cdm = Role::create(['name' => 'cdm']);
        $role_executive_alpema = Role::create(['name' => 'executive-alpema']);

        $permissions = collect([
            'index users',
            'create users',
            'edit users',
            'index users teachers',
            'create users teachers',
            'edit users teachers',
            'index users principals',
            'create users principals',
            'edit users principals',
            'destroy all users',
            'index craft books',
            'index review books',
            'index published books',
            'create books',
            'edit books',
            'destroy books',
            'send books to review',
            'publish books',
            'unpublish books',
            'see catalogue books',
            'see book',
            'see units book',
            'see the activities of the units of the books',
            'index units',
            'create units',
            'edit units',
            'destroy units',
            'index activities',
            'create activities',
            'edit activities',
            'destroy activities',
            'index sections',
            'create sections',
            'edit sections',
            'destroy sections',
            'sections preview',
            'see catalogue digital books',
            'see my class rooms',
            'create class rooms',
            'unique',
            'configs',
            'resources',
            'reports',
            'index advisors',
            'see activity apd',
            'apd create visit',
            'apd edit visit',
            'apd delete visit',
            'apd add rate',
            'seller apd see my activity',
            'seller apd create my visit',
            'seller apd edit my visit',
            'seller apd delete my visit',
            'sap sale order',
            'create workshop',
            'edit workshop',
            'delete workshop',
            'see the workshop',
            'register in the workshop',
            'index workshop',
            'sap create sale order',
            'sap edit sale order',
            'sap delete sale order',
            'sap send to sap',
            'see catalogue literary books',
            'index evaluations',
            'create evaluations',
            'edit evaluations',
            'delete evaluations',
            'see evaluation preview',
            'publish evaluation',
            'apply assessment',
            'index resources',
            'create resources',
            'edit resources',
            'delete resources',
            //
        ]);

        $permissions_by_role = [
            'admin' => [
                'index users',
                'create users',
                'edit users',
                'index users teachers',
                'create users teachers',
                'edit users teachers',
                'index users principals',
                'create users principals',
                'edit users principals',
                'destroy all users',
                'index craft books',
                'index review books',
                'index published books',
                'create books',
                'edit books',
                'destroy books',
                'send books to review',
                'publish books',
                'unpublish books',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'index units',
                'create units',
                'edit units',
                'edit units',
                'destroy units',
                'index activities',
                'create activities',
                'edit activities',
                'destroy activities',
                'index sections',
                'create sections',
                'edit sections',
                'destroy sections',
                'sections preview',
                'see catalogue digital books',
                'see my class rooms',
                'create class rooms',
                'unique',
                'configs',
                'resources',
                'reports',
                'index advisors',
                'see activity apd',
                'apd create visit',
                'apd edit visit',
                'apd delete visit',
                'apd add rate',
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
                'sap sale order',
                'create workshop',
                'edit workshop',
                'delete workshop',
                'see the workshop',
                'register in the workshop',
                'index workshop',
                'sap create sale order',
                'sap edit sale order',
                'sap delete sale order',
                'sap send to sap',
                'see catalogue literary books',
                'index evaluations',
                'create evaluations',
                'edit evaluations',
                'delete evaluations',
                'see evaluation preview',
                'publish evaluation',
                'apply assessment',
                'index resources',
                'create resources',
                'edit resources',
                'delete resources',
            ],

            'supervisor' => [
                'index craft books',
                'index review books',
                'index published books',
                'create books',
                'edit books',
                'destroy books',
                'send books to review',
                'publish books',
                'unpublish books',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'index units',
                'edit units',
                'index activities',
                'edit activities',
                'index sections',
                'edit sections',
                'sections preview',
                'see catalogue digital books',
                'resources',
                'reports',
                'index evaluations',
                'see evaluation preview',
            ],

            'curator' => [
                'index craft books',
                'index published books',
                'create books',
                'edit books',
                'destroy books',
                'send books to review',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'index units',
                'create units',
                'edit units',
                'destroy units',
                'index activities',
                'create activities',
                'edit activities',
                'destroy activities',
                'index sections',
                'create sections',
                'edit sections',
                'destroy sections',
                'sections preview',
                'see catalogue digital books',
                'resources',
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
                'index evaluations',
                'create evaluations',
                'edit evaluations',
                'delete evaluations',
                'see evaluation preview',
            ],

            'seller' => [
                'index users teachers',
                'create users teachers',
                'edit users teachers',
                'index users principals',
                'create users principals',
                'edit users principals',
                'destroy all users',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'see catalogue digital books',
                'resources',
                'reports',
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
                'sap sale order',
                'sap create sale order',
                'sap edit sale order',
                'sap delete sale order',
            ],

            'school-principal' => [
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'see catalogue digital books',
                'see my class rooms',
                'create class rooms',
                'resources',
                'see the workshop',
                'register in the workshop',
            ],

            'teacher' => [
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'see catalogue digital books',
                'see my class rooms',
                'create class rooms',
                'resources',
                'see the workshop',
                'register in the workshop',
            ],

            'student' => [
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'see my class rooms',
                'apply assessment',
            ],

            'admregional' => [
                'index users',
                'create users',
                'edit users',
                'index users teachers',
                'create users teachers',
                'edit users teachers',
                'index users principals',
                'create users principals',
                'edit users principals',
                'destroy all users',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'see catalogue digital books',
                'resources',
                'index advisors',
                'see activity apd',
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
                'sap sale order',
                'sap create sale order',
                'sap edit sale order',
                'sap delete sale order',
                'sap send to sap',
            ],

            'corrector' => [
                'index review books',
                'index published books',
                'edit books',
                'see catalogue books',
                'see book',
                'see units book',
                'see the activities of the units of the books',
                'index units',
                'create units',
                'edit units',
                'destroy units',
                'index activities',
                'create activities',
                'edit activities',
                'destroy activities',
                'index sections',
                'create sections',
                'edit sections',
                'destroy sections',
                'sections preview',
                'see catalogue digital books',
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
                'index evaluations',
                'create evaluations',
                'edit evaluations',
                'delete evaluations',
                'see evaluation preview',
            ],

            'cdm' => [
                'create workshop',
                'edit workshop',
                'delete workshop',
                'see the workshop',
                'index workshop',
                'index evaluations',
                'create evaluations',
                'edit evaluations',
                'delete evaluations',
                'see evaluation preview',
            ],

            'alpema' => [
                'seller apd see my activity',
                'seller apd create my visit',
                'seller apd edit my visit',
                'seller apd delete my visit',
            ],
        ];

        $permissions = $permissions->map(function ($permission) {
            return ['name' => $permission, 'guard_name' => 'web'];
        });

        Permission::insert($permissions->toArray());

        $role_admin->syncPermissions($permissions_by_role['admin']);
        $role_supervisor->syncPermissions($permissions_by_role['supervisor']);
        $role_curator->syncPermissions($permissions_by_role['curator']);
        $role_seller->syncPermissions($permissions_by_role['seller']);
        $role_school_principal->syncPermissions($permissions_by_role['school-principal']);
        $role_teacher->syncPermissions($permissions_by_role['teacher']);
        $role_student->syncPermissions($permissions_by_role['student']);
        $role_adm_regional->syncPermissions($permissions_by_role['admregional']);
        $role_corrector->syncPermissions($permissions_by_role['corrector']);
        $role_cdm->syncPermissions($permissions_by_role['cdm']);
        $role_executive_alpema->syncPermissions($permissions_by_role['alpema']);
    }
}
